clarify how a term `payload` is used
oauthstuff/draft-selective-disclosure-jwt pull request #43
Opened 2022-06-13 00:38 UTC by Sakurann

As pointed out in Issuer #26, a term payload has been used to characterize an object with a set of claims that the Issuer is trying to disclose using SD-JWT. Also clarifies when it is an example of an entire SD-JWT payload or just an `_sd` object.

Note: I would suggest using only Example 1 of 'flat' SD-JWT in the main text and move Example 2 to the Annex.

2022-06-13 09:26 UTC, danielfett requested changes

2022-06-13 09:26 UTC, danielfett commented on main.md
> +In this example, the Issuer is using a following object as a set of claims to issue to the Holder:
```suggestion
In this example, the Issuer is using the following object as a set of claims to issue to the Holder:
```

2022-06-13 09:26 UTC, danielfett commented on main.md
> +The difference between the examples is how an `address` claim is disclosed.
```suggestion
The difference between the examples is how the `address` claim is disclosed.
```

2022-06-13 10:55 UTC, selfissued commented
I agree with @danielfett 's suggested changes.

2022-06-13 10:59 UTC, selfissued approved these changes
I'm good to go with this once @danielfett 's suggestions have been incorporated.

2022-06-13 12:11 UTC, selfissued approved these changes
Please see the content of my previous approval.  I clicked the wrong part of the page and cleared my "reviewed" status.

2022-06-14 16:16 UTC, bc-pi approved these changes

2022-06-16 10:31 UTC, merged