feat: additional security considerations
oauthstuff/draft-selective-disclosure-jwt pull request #67
Opened 2022-06-18 10:00 UTC by peppelinux

# Security Considerations

- feat: Minimum length of the salt
- feat: weak hash algorithms to not use

2022-06-18 12:35 UTC, peppelinux commented
mh ... we already have `MUST contain at least 128 bits of pseudorandom data` in Section [SD_JWT Claims](https://github.com/oauthstuff/draft-selective-disclosure-jwt/blob/master/main.md#sd-jwt-claims)

2022-06-20 13:10 UTC, danielfett requested changes

2022-06-20 13:10 UTC, danielfett commented on main.md
> +revealed fundamental weaknesses and they should no longer be used.
```suggestion
revealed fundamental weaknesses and they MUST NOT be used.
```

2022-06-20 13:10 UTC, danielfett commented on main.md
> +The length of the randomly-generated portion of the salt shall be at least 128 bits.
```suggestion
The length of the randomly-generated portion of the salt MUST be at least 128 bits.
```

2022-06-23 15:08 UTC, peppelinux commented
@danielfett I commited your suggestion

I'm not sure that the normative language could be used in the considerations but it's good anyway to me, it's intellegibile :)

2022-06-23 15:39 UTC, Sakurann approved these changes

2022-06-23 15:41 UTC, merged